### ISSUE TITLE
[Feature] 🍠 considered a potato maybe?

### ISSUE THREAD

**Issue by meadowsys** [PonyEventsFederation/CanniJS#114]
![canni thinking emote](https://cdn.discordapp.com/emojis/746316563220791296.png?size=64)![smartato emote](https://cdn.discordapp.com/emojis/615260317769007134.png?size=64)

![sweet potato screenshot](https://user-images.githubusercontent.com/49562048/111852736-562af700-88d5-11eb-8a70-566adabf45d6.png)

**Comment by ChrisFhey** [comment]
🍠 👌
