### ISSUE TITLE
[Bug] Bot crashes on special command combo

### ISSUE THREAD

**Issue by DrNachtschatten** [PonyEventsFederation/CanniJS#116]
Command @bot compliment @user works as intended
but the bot crashes on the following sequence or one of those commands:

(replying to @bot) compliment @user

(replying to @user) @bot compliment

Further testing shows that the bot crashes likely only at the second one.

Screenshot related.

![image](https://user-images.githubusercontent.com/65015456/112628204-dbad2a80-8e32-11eb-9875-8ee0a3d10a63.png)

**Comment by ChrisFhey** [comment]
@DrNachtschatten Thank you for reporting the issue. It appears that Canni took issue to the fact that no user was explicitly mentioned and crashed on that. Should be fixed now.
