### ISSUE TITLE
[Feature] Add database to Canni

### ISSUE THREAD

**Issue by ChrisFhey** [PonyEventsFederation/CanniJS#117]
### Describe the feature
Let Canni connect to a database to keep track of cooldowns across restarts.

### Why would you like this feature to be added?
Canni currently keeps track of her cooldowns in memory for megaboops, megahugs, etc...
This means that she loses these cooldowns upon a restart, be it intentional or not.
Adding a database to keep track of this data prevents people from circumventing her cooldowns.

**Comment by ChrisFhey** [comment]
Initial change has been made to megaboop logic. Next on the list is adding a way to clear the data at midnight.

**Comment by ChrisFhey** [comment]
Added an event to mysql database that _should_ clear the timeouts every day at 23:59. (Keyword: should)

**Comment by meadowsys** [comment]
im looking at the code, wouldn't it be better to have a persistent connection to the db instead of connecting and disconnecting everytime?

**Comment by ChrisFhey** [comment]
While testing I've noticed the server kills the connection after its timeout, and crashes the app when not closing the connection. 
For now I'll leave it like this so I can test if everything works. I'll look at connection pooling afterwards to fix the crashing.
