### ISSUE TITLE
[Feature] enable/disable modules using environment variables

### ISSUE THREAD

**Issue by meadowsys** [PonyEventsFederation/CanniJS#118]
### Describe the feature
maybe instead of hardcoding which modules are enabled, there can be a list of modules inside an environment variable that canni can use to enable/disable some modules

### Why would you like this feature to be added?
we can easily enable/disable certain modules without having to commit something, its just a matter of changing the environment variable and restarting her

**Comment by ChrisFhey** [comment]
That's a great idea.
I'll work on implementing this when I've time. 👌

**Comment by meadowsys** [comment]
i got some implementation already lol, meant to write some sort of mockup but it became fully functional

i think i'm gonna test and then commit it

**Comment by meadowsys** [comment]
done uwu

how it works: it has an array with module names in it. first it checks `DISABLED_MODULES` and removes those from the array, then it checks `ENABLED_MODULES` and adds them to the array if they aren't already, then it registers them and starts

format of the environment variables is comma-seperated values, so like `Activity, DevCommands, Fanta` and is case sensitive i think

I also went and added `Activity` into the array of default enabled arrays, since its easier to disable using the env var now
