### ISSUE TITLE
[Request] Instead of just booping and being bored

### ISSUE THREAD

**Issue by FuzzyPones** [PonyEventsFederation/CanniJS#15]
When canni is bored pick latest message writer to ask to play a game of rock paper scissors.

User: bla bla
Canni: I'm bored, @User let's play a game of rock paper scissors.
Canni: I have already chosen what to use, type @Canni and 👊,🖐 or ✌ 

User: @Canni 🖐

Canni: @User Hehe, you lost, I chose ✌
Or
Canni: @User Congrats you won! Here is a hug 🤗 

Maybe add scoring system? Probably too much and not feasable because random

**Comment by ChrisFhey** [comment]
thanks for the suggestion, Fuzzy poner. It's added and is active in production.
Can also trigger her with a mention `@Canni let's play a game`.
